[package]
name = "rust-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
bytemuck = "1.23.1"

[dependencies.sdl2]
features = ["use_mac_framework"]
version = "0.38.0"  # Whichever version you are using

